### ISSUE TITLE
unable to use single project selection

### ISSUE THREAD

**Issue by murad073** [murad073/SmartAccount#28] opened 2012-05-01 10:39 UTC
in project head management uc, if only one project exists, no way to get refresh. the project is always selected, even if click, SelectedProject is not set.  Solve the problem.

**Comment by jakaria42** [comment] 2012-05-05 18:08
This is a duplicate of issue# 30. There is a clearer description of the problem.
Closing.

**Closed as completed by jakaria42** 2012-05-05 18:08 UTC
Labels: bug, duplicate
